name: Deploy Complex Multi Project
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build imagem de testes
        run: docker build -t pedropadilhaportella/react-test -f ./client/Dockerfile.dev ./client

      - name: Execucao dos testes
        run: docker run -e CI=true pedropadilhaportella/react-test npm run test -- --coverage

      - name: Build imagens finais
        run: |
          docker build -t pedropadilhaportella/multi-client ./client
          docker build -t pedropadilhaportella/multi-nginx ./nginx
          docker build -t pedropadilhaportella/multi-server ./server
          docker build -t pedropadilhaportella/multi-worker ./worker

      - name: Push imagens
        run: |
          docker push pedropadilhaportella/multi-client
          docker push pedropadilhaportella/multi-nginx
          docker push pedropadilhaportella/multi-server
          docker push pedropadilhaportella/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: pedropadilhaportella/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-complex
          environment_name: Multigh-env
          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
